<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Denied Decision</name>
  <uuid>8a2f0380-3d72-4cc3-8e28-241e00328bbc</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Validate Type of Goods' is denied 
	or 'Validate Time Window' is denied 
then
	set decision to denied ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
