<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Manual Decision</name>
  <uuid>c72d7742-08ee-4f20-b584-eb320c8e5189</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Validate Type of Goods' is manual 
	or 'Validate Time Window' is manual 
then
	set decision to manual ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
