<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>b62b34d8-347a-46b0-828a-1f37aeecb30f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Refund Response where 
	the decision is approved ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
